### ISSUE TITLE
Error occured when trying to finetune the pre-trained model on hmdb51

### ISSUE THREAD

**Issue by wenjie710** [facebookresearch/R2Plus1D#19]
Hey,
I am trying to finetune the model on hmdb, but when I run the scripts tools/train_net.py, an error occured. Do you know how to fix it? Which version of caffe2 do you use, the official caffe2 or your personal fork of caffe2?

Traceback (most recent call last):
  File "train_net.py", line 501, in <module>
    main()
  File "train_net.py", line 496, in main
    Train(args)
  File "train_net.py", line 280, in Train
    net_type=('prof_dag' if args.profiling == 1 else 'dag'),
  File "/home/wenjie/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 32, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/wenjie/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 208, in Parallelize
    input_builder_fun(model_helper_obj)
  File "train_net.py", line 268, in add_video_input
    use_local_file=args.use_local_file,
  File "/home/wenjie/R2Plus1D/utils/model_helper.py", line 127, in AddVideoInput
    data, label = model.net.VideoInput(
  File "/home/wenjie/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/core.py", line 2067, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []

**Comment by dutran** [comment]
@wenjie710 the latest caffe2 should have VideoInputOp (https://github.com/pytorch/pytorch/tree/master/caffe2/video)

**Comment by wenjie710** [comment]
Thanks very much! It works now.

**Comment by kateiyas** [comment]
@wenjie710 Can you write how you solved this issue, please? I also see it.

**Comment by orionr** [comment]
Unfortunately Caffe2 will need to be built from source in order to include an OpenCV and ffmpeg dependency required for those operators to be built. The binary install doesn't include these because we didn't want the additional dependencies. cc @pjh5
