### ISSUE TITLE
Method VideoInput is not a registered operator

### ISSUE THREAD

**Issue by DuJiajun1994** [facebookresearch/R2Plus1D#24]
I use Pre-Built Binaries to install Caffe2 (conda install -c caffe2 caffe2-cuda8.0-cudnn7). During feature extraction, I get an error as following. Why is VideoInput not registered?

Traceback (most recent call last):
  File "tools/extract_features.py", line 292, in <module>
    main()
  File "tools/extract_features.py", line 287, in main
    ExtractFeatures(args)
  File "tools/extract_features.py", line 118, in ExtractFeatures
    devices=gpus,
  File "/home/dujiajun/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 32, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/dujiajun/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 208, in Parallelize
    input_builder_fun(model_helper_obj)
  File "tools/extract_features.py", line 94, in input_fn
    use_local_file=args.use_local_file,
  File "/home/dujiajun/R2Plus1D/lib/utils/model_helper.py", line 120, in AddVideoInput
    data, label, video_id = model.net.VideoInput(
  File "/home/dujiajun/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/core.py", line 2067, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []

**Comment by dutran** [comment]
Make sure that you compile caffe2 correctly and set the LIBRARY_PATH and PYTHON_PATH correctly point to caffe2. Please check https://caffe2.ai/docs/faq.html
