### ISSUE TITLE
Questions about add new layers

### ISSUE THREAD

**Issue by XiongChengxin** [facebookresearch/R2Plus1D#32]
Dear author,
Thanks for your great work. I met errors when I tried to add new layers to R2Plus1D， could you give me some advice? We know the temporal dimension of the output of the final conv is 1/8 of the original, so I want to add ConvTranspose layer to make it back. My code and error message are as follows, I wrote all of the needed arguments but I still met the same error, so I have no idea what I missed. Any help would be highly appreciated.

My code:
upconv = brew.conv_transpose(
    model,
    blob_in = 'final_avg'
    blob_out = 'upconv'
    dim_in = 512,
    dim_out = 2048,
    kernels = [4,1,1],
    weight_init = None,
    bias_init = None,
    use_cudnn = True,
    order = 'NCHW',
    cudnn_exhaustive_search = False,
    ws_nbytes_limit = None, 
    strides = [2,1,1],
    pads = [1,0,0]
)

Error message:
Traceback (most recent call last):
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 528, in <module>
    main()
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 523, in main
    Train(args)
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 303, in Train
    net_type=('prof_dag' if args.profiling == 1 else 'dag'),
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/data_parallel_model.py", line 32, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/data_parallel_model.py", line 209, in Parallelize
    losses = forward_pass_builder_fun(model_helper_obj, loss_scale)
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 240, in create_model_ops
    pred_layer_name=args.pred_layer_name,
  File "../lib/models/model_builder.py", line 134, in build_model
    is_test=is_test,
  File "../lib/models/r3d_model.py", line 101, in create_model
    is_decomposed=(model_name == 'r2plus1d'),
  File "../lib/models/r3d_model.py", line 228, in create_r3d
    CDC1 = brew.conv_transpose(
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/brew.py", line 107, in scope_wrapper
    return func(*args, **new_kwargs)
TypeError: conv_transpose() takes at least 6 arguments (11 given)

**Comment by dutran** [comment]
It said "conv_transpose() takes at least 6 arguments (11 given)" which mean you gave more arguments than needed.
